### ISSUE TITLE
Feature Request: Import from CSV

### ISSUE THREAD

**Issue by KLD997** [emavgl/oinkoin#107]
Would like the ability to import my bank CSV's so I am not adding each transaction manually, still fine to manually categorize the transactions but just a way to import them as a bulk from a .csv file

Looks like this is related to #13

**Comment by emavgl** [comment]
Hi @KLD997, thanks for opening an issue for that.

As mentioned in the other issue, importing a CSV is challenging because I would need to know the structure in advance, or prompting the user to define the schema within the app itself.

Could it be an option for you converting the CSV data to the JSON format specified in #13 ?

**Comment by emavgl** [comment]
It should be fixed with https://github.com/emavgl/oinkoin/releases/tag/1.0.57 - please reopen the ticket or leave a comment if there is still anything not working. Thanks again for reporting.
