### ISSUE TITLE
Feature Request: Option to set fingerprint/number pin lock

### ISSUE THREAD

**Issue by adarsh1001** [emavgl/oinkoin#14]
First up, great app!

Since this app stores sensitive information about income and expenses, it would be great if we can have an option to lock the app with a fingerprint/number pin lock (whatever is set on the device by the user).

**Comment by emavgl** [comment]
Hi! I am happy you like the app and thanks for the feedback! 😊

I think it is a valid point and I was actually thinking of it some time ago. However than I thought that would not be that much helpful, because your phone needs to be unlocked first to open the app. So which benefit would it bring unlocking it twice?

Do you have in mind a concrete scenario on why having it at the app level would bring more security?

**Comment by adarsh1001** [comment]
Actually, a lot of sensitive apps have this option. Be it chat apps like Signal/WhatsApp or almost all banking/payment apps or password managers like Proton Pass, etc. The idea is, if you give your phone to someone for whatever reason or it gets left unlocked, they cannot access your sensitive information as it requires a 2nd authentication, kind of like why we do 2FA.

This need not be the default behavior of course, just an option that those who want can enable.

**Comment by DSiekmeier** [comment]
Just my opinion: this feature request would be useful when there is an encrypted data storage. Otherwise "Mallory" (a malicious person) just takes the data file to see the secrets.

**Comment by emavgl** [comment]
At the moment, data are stored in the app folder, isolated and protected by the Android system. When in the future would be possible to do a backup in a dedicated folder, having a password for encrypting the file would also make sense. In this case, I can't use the fingerprint, since you probably would also like to read the encrypted file from your PC or in another device.

**Comment by emavgl** [comment]
Done https://github.com/emavgl/oinkoin/releases/tag/1.0.73 - I am closing the issue but feel free to comment.
